# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31bfe3d6fbcdaa36379dbef09a92a8a2e223c2dfad7fb9136f83befe4f4cc1946cc622f100f145aaae878eebada960368d633a38535074ccae919333c5f49800

test:
  secret_key_base: 290a9a0669dfcab6ccb89548283c15d9fe4e8d83005d0fb395c6b1b7ff46bfa82713ec2e618565df803d2e215d17366e9557108cfa032477fbfb9c1f766a8e79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
